### ISSUE TITLE
Transition persisted elements

### ISSUE THREAD

**Issue by daltonrooney** [jonhue/turbolinks-animate#28]
**Is your feature request related to a problem? Please describe.**
I'm trying to transition between two pages where a solid-color background banner element persists but changes color. Even though I've added a transition via CSS, it doesn't take place because the actual element is replaced in the DOM.

**Describe the solution you'd like**
It would be cool to have some way to define specific transitions on elements between pages as a data attribute. Specifically height and background color in this example, but I'm sure other attributes would be helpful as well.

**Comment by jonhue** [comment]
I like your suggestion.

However, I don't think this is doable with how this package handles the rendering of new content. As of now, it only applies transitions before and after new content is rendered. This feature, however, would need to delay the rendering of new content, thus interfere with the browser-way of doing things.

I'd be happy to review a pull request, but sadly at the moment I do not have the time to to tackle this on my own.

**Comment by daltonrooney** [comment]
I thought about this a bit more and it seems like it may be possible to accomplish without even modifying turbolinks-animate. Just add a data attribute to the element whose style you want to persist, and before the page transitions, inject a new style tag into the head to capture the current element style (background-color, height, etc). 

Once Turbolinks has completed the new page render, you can delete the style tag and any CSS transitions will take over. 

I’ll give it a try today and see if I can get something working.

**Comment by jonhue** [comment]
Sounds good!

**Comment by daltonrooney** [comment]
Hey, so I did manage to get this working! Thought I would share in case it's of value to anyone else.

For the markup, each element to be transitioned needs a unique ID on the page, and be the same from page to page. It might looks something like this:

```
 <header id="banner" data-turbolinks-animate-persist-itself="true" data-transition="background-color">
   <h1>Title</h1>
</header>
```

Some simple CSS for the transition itself:

```
#banner {
  transition: background-color 1s ease-in-out;
}
.page-1 #banner {
  background-color: #96858f;
}
.page-2 #banner {
  background-color: #6D7993;
}
```

etc., etc.

And here's the JS I used to initiate the transitions. Would appreciate any feedback if you notice something that could be improved... I'm still learning the ins and outs of Turbolinks.

```
document.addEventListener( 'turbolinks:before-render', function() {
  var els = document.querySelectorAll('[data-transition]');
  if ( els.length > 0 ) {
    var css = '', head = document.head, style = document.createElement('style');
    for (var i = 0; i < els.length; i++) {
      var el = els[i], 
      property = el.dataset.transition,
      value = getComputedStyle(el).getPropertyValue(property);
      css += '#' + el.id + '{'+property+':'+value+';}';
    }
    style.id = 'animate-transition';
    style.type = 'text/css';
    style.appendChild(document.createTextNode(css));
    head.appendChild(style);
  }
});

document.addEventListener( 'turbolinks:render', function() {
  var el = document.getElementById('animate-transition');
  if ( el !== null ) {
    setTimeout(function(){ el.remove(); }, 1);
  }
});
```

For example, that setTimeout function in the turbolinks:render listener feels a bit hacky, but I couldn't find a better event to hook into.

Here's a quick example of it in action:

![2018-10-30 17-53-15 2018-10-30 17_56_41](https://user-images.githubusercontent.com/742045/47759717-1e707580-dc6e-11e8-836f-3be99cb4497f.gif)

Cheers!

**Comment by jonhue** [comment]
Looks fantastic!

I played around a little and altered your code a little:

```javascript
document.addEventListener( 'turbolinks:before-render', function(event) {
    document.querySelectorAll('[data-transition]').forEach((element) => {
        let property = element.dataset.transition,
             matchingElements = event.data.newBody.querySelectorAll(element.tagName + '[data-transition]'),
             newElement = null;
        if (matchingElements.length == 1) {
            newElement = matchingElements[0];
        } else if (matchingElements.length > 1) {
            newElement = event.data.newBody.querySelector('#' + element.id);
        }
        if (!newElement)
            return;

        newElement.style[cssPropertyToCamelCase(property)] = getComputedStyle(element).getPropertyValue(property);
    });
});
document.addEventListener( 'turbolinks:render', function(event) {
    document.querySelectorAll('[data-transition]').forEach((element) => {
        setTimeout(() => element.style[cssPropertyToCamelCase(element.dataset.transition)] = null, 1);
    });
});

function cssPropertyToCamelCase(cssProperty) {
    return cssProperty.replace(/-([a-z])/gi, function(s, group1) {
        return group1.toUpperCase();
    });
};
```

What I mainly did, is I moved from adding a new `style` tag to declaring styles inline.

Most of this is actually just fluff I added, to make declaring id's optional as long as you have only one HTML tag of a kind with a data-transition attribute.

The `setTimeout` hack, seems to be necessary though.

What do you think?

**Comment by daltonrooney** [comment]
Looks awesome! I agree inline is a more elegant solution and should help with CSS scope. Really glad to be able to use this technique with turbolinks-animate, it definitely gives the site I'm working a smoother feel. Will share a link when the project goes live!

**Comment by jonhue** [comment]
Would love to see how your project ends up!

I think I might add this feature to this package. Afterall, it's about allowing for animated page transitions with Turbolinks. It works quite well with the existing options.
