### ISSUE TITLE
Demo is not available

### ISSUE THREAD

**Issue by ejemba** [jonhue/turbolinks-animate#29]
**Describe the bug**
The demo of turbolinks-animate is not avalaible.

**To Reproduce**
1. Go to 'https://jonhue.me/' the demo link
2. See error

**Expected behavior**
A sample of the library in use.

**Screenshots**
noppe

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jonhue** [comment]
That's because my website uses free dyno hours on Heroku. It'll be available again the beginning of next month.
