### ISSUE TITLE
Error with TurbolinksAnimate.appear();

### ISSUE THREAD

**Issue by tydoo** [jonhue/turbolinks-animate#45]
![image](https://user-images.githubusercontent.com/50534204/57576660-a4fbe000-7465-11e9-928d-baf709a0aa09.png)

Turbolinks-animate not work

**Comment by jonhue** [comment]
Could you detail your template and initialization of turbolinks-animate?

**Comment by tydoo** [comment]
I use browserify.

```js
global.Turbolinks = require('turbolinks');
Turbolinks.start();
require('turbolinks-animate');
```

This code no work to :
```js
var turbolinksAnimate =   require('turbolinks-animate');
```

**Comment by tydoo** [comment]
And when i use uglifyjs, i have this error : 

```
Error: Cannot find module
```

You dont use the module export : 

```js
module.exports = function() { ... }
```

**Comment by jonhue** [comment]
After you imported this package `TurbolinksAnimate` should be available in the global scope (as long as you're in a browser). Just use `import 'turbolinks-animate'`.
