### ISSUE TITLE
Weird doc and usage

### ISSUE THREAD

**Issue by equinusocio** [jonhue/turbolinks-animate#78]
**Is your feature request related to a problem? Please describe.**
How is supposed to use this lib?

I'm using turbolinks on a static site, but i can't figure out how to use this. I just have a couple of html pages and 4 lines of js, but the readme doesn't tell much info under the usage section. This is my js, and turbolinks-animate doesn't work. What i'm missing?

```js
import Turbolinks from 'turbolinks'
import TurbolinksAnimate from 'turbolinks-animate'

/**
 * Init Turbolinks within the site
 */
Turbolinks.start()
TurbolinksAnimate.init({ animation: 'fadeinright' })
```

**Comment by jonhue** [comment]
Use

```js
import 'turbolinks-animate'

document.addEventListener('turbolinks:load', () => {
    TurbolinksAnimate.init({ ... })
})
```

**Comment by equinusocio** [comment]
Don't you think the README should include these instructions?

**Comment by jonhue** [comment]
Happy to review a pull request if you want to add it to the readme 🙂
