### ISSUE TITLE
init is not a function

### ISSUE THREAD

**Issue by zhi8617** [jonhue/turbolinks-animate#94]
**Describe the bug**
Uncaught TypeError: TurbolinksAnimate.init is not a function

**To Reproduce**
1 . npm i turbolinks-animate
2. In app.js file.
const NProgress = require("nprogress");
const TurbolinksAnimate = require("turbolinks-animate");

window.addEventListener("turbolinks:load", () => {
 TurbolinksAnimate.init({
        animation: "fadeinright",
        duration: "1s",
        delay: 1000
    });
});

So I got the wrong message .
I don't know if this is a mistake or if I'm overlooking something.

Thank .

**Comment by euxx** [comment]
I just try this library, I found from related [turbolinks-animate-rails](https://github.com/jonhue/turbolinks-animate-rails), it seems the `TurbolinksAnimate.init` function  must add a `element` attribute, like this:
```js
import 'turbolinks-animate';
document.addEventListener( 'turbolinks:load', function() {
    TurbolinksAnimate.init({ element: document.querySelector('body') });
});
```
Also you need add and import [animate.css](https://animate.style/) to have the animations, like this:
```css
@import 'animate.css'
```

**Comment by jonhue** [comment]
@euxx is right! I'm working on updating the docs and making it easier to get started!
